#!/bin/bash

CPU="armv7le"
CPUDIR="armle-v7"
BUSUFFIX="armv7"

CC_COMMAND="$QNX_HOST/usr/bin/qcc"
BUILDTYPE="Release"

QNX_INCLUDE="$QNX_TARGET/usr/include"
QNX_USR_LIB="$QNX_TARGET/$CPUDIR/usr/lib"
QNX_LIB="$QNX_TARGET/$CPUDIR/lib"

COMP_PATHS=" \
    -Wl,-rpath-link,$QNX_LIB \
    -Wl,-rpath-link,$QNX_USR_LIB"


COMP_PATHS="$COMP_PATHS \
    -Wl,-rpath-link,$QNX_LIB \
    -Wl,-rpath-link,$QNX_USR_LIB"


COMP_PATHS="$COMP_PATHS \
    -L$QNX_LIB \
    -L$QNX_USR_LIB"

if [ "$CCWRAP" ] ; then
    CMAKE_EXTRA_OPTIONS=" \
        -DCMAKE_C_COMPILER_ARG1=qcc \
        -DCMAKE_CXX_COMPILER_ARG1=qcc \
        $CMAKE_EXTRA_OPTIONS"
    CC_COMMAND="$CCWRAP"
fi

EXTRA_FLAGS=" \
    -Wno-psabi \
    -lang-c++ \
    -fstack-protector \
    -fstack-protector-all \
    -mcpu=cortex-a9 \
    -Wno-psabi \
    -Wall \
    -W \
    -D_REENTRANT \
    -DQT_NO_IMPORT_QT47_QML \
    -DQ_OS_BLACKBERRY \
    -DQT_DECLARATIVE_LIB \
    -DQT_SCRIPT_LIB \
    -DQT_SVG_LIB \
    -DQT_SQL_LIB \
    -DQT_XMLPATTERNS_LIB \
    -DQT_XML_LIB \
    -DQT_GUI_LIB \
    -DQT_NETWORK_LIB \
    -DQT_CORE_LIB \
    -DQT_SHARED"

if [ `uname` == "Darwin" ] ; then
    CMAKE_EXTRA_OPTIONS=" \
        -DCMAKE_SKIP_RPATH='ON' \
        $CMAKE_EXTRA_OPTIONS"
fi

if [ "$DEV_BUILD" == "1" ]; then
    CMAKE_EXTRA_OPTIONS=" \
        -DDEV_BUILD=1 \
        $CMAKE_EXTRA_OPTIONS"
fi

if [ ! -z "$PROFILE" ] ; then
    CMAKE_EXTRA_OPTIONS="$CMAKE_EXTRA_OPTIONS -DPROFILING=1"
fi

cmake \
    -DCMAKE_SYSTEM_PROCESSOR="$CPUDIR" \
    -DCMAKE_SYSTEM_NAME="QNX" \
    -DCMAKE_SYSTEM_VERSION="1" \
    -DCMAKE_BUILD_TYPE="$BUILDTYPE" \
    -DCMAKE_C_COMPILER="$CC_COMMAND" \
    -DCMAKE_CXX_COMPILER="$CC_COMMAND" \
    -DCMAKE_C_FLAGS="-Vgcc_nto$CPU -g $COMP_PATHS" \
    -DCMAKE_CXX_FLAGS="-Vgcc_nto${CPU}_cpp-ne -g -lang-c++ $EXTRA_FLAGS $COMP_PATHS" \
    -DCMAKE_INCLUDE_PATH="$QNX_INCLUDE" \
    -DCMAKE_LIBRARY_PATH="$QNX_LIB;$QNX_USR_LIB" \
    -DCMAKE_INSTALL_PREFIX="bb10" \
    -DCMAKE_AR="$QNX_HOST/usr/bin/nto$BUSUFFIX-ar" \
    -DCMAKE_RANLIB="$QNX_HOST/usr/bin/nto$BUSUFFIX-ranlib" \
    -DCMAKE_LD="$QNX_HOST/usr/bin/nto$BUSUFFIX-ld" \
    -DCMAKE_LINKER="$QNX_HOST/usr/bin/nto$BUSUFFIX-ld" \
    -DECLIPSE_CDT4_GENERATE_SOURCE_PROJECT=TRUE \
    -DWITH_KDE=OFF \
    -DWITH_SYSLOG=OFF \
    -DWITH_PHONON=OFF \
    -G"Eclipse CDT4 - Unix Makefiles" \
    $CMAKE_EXTRA_OPTIONS \
    $3 
